jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.repo.full_name == github.repository && github.event.pull_request.head.ref || '' }}
      - run: cat foo.txt > bar.txt
      - run: git config --global user.email "you@example.com"
      - run: git config --global user.name "Your Name"
      - run: git add .
      - run: 'git commit -m "fix: update files"'
      - run: git push
name: build
on:
  pull_request: {}
  push:
    branches:
      - master
